export const FETCHING_USER = "FETCHING_USER";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

export const FETCHING_GAMES = "FETCHING_GAMES";
export const FETCHING_GAMES_SUCCESS = "FETCHING_GAMES_SUCCESS";
export const FETCHING_GAMES_FAIL = "FETCHING_GAMES_FAIL";

export const CREATING_GAME = "CREATING_GAME";
export const CREATING_GAME_SUCCESS = "CREATING_GAME_SUCCESS";
export const CREATING_GAME_FAIL = "CREATING_GAME_FAIL";

export const DELETING_GAME = "DELETING_GAME";
export const DELETING_GAME_SUCCESS = "DELETING_GAME_SUCCESS";
export const DELETING_GAME_FAIL = "DELETING_GAME_FAIL";

export const FETCHING_CURR_GAME = "FETCHING_CURR_GAME";
export const SET_CURR_GAME = "SET_CURR_GAME";
export const ADD_PLAYER_TO_CURR_GAME = "ADD_PLAYER_TO_CURR_GAME";
export const ADD_WINNER = "ADD_WINNER";
