export const LOGGING_IN = "LOGGING_IN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

export const FETCHING_GAMES = "FETCHING_GAMES";
export const FETCHING_GAMES_SUCCESS = "FETCHING_GAMES_SUCCESS";
export const FETCHING_GAMES_FAIL = "FETCHING_GAMES_FAIL";

export const CREATING_GAME = "CREATING_GAME";
export const CREATING_GAME_SUCCESS = "CREATING_GAME_SUCCESS";
export const CREATING_GAME_FAIL = "CREATING_GAME_FAIL";

export const DELETING_GAME = "DELETING_GAME";
export const DELETING_GAME_SUCCESS = "DELETING_GAME_SUCCESS";
export const DELETING_GAME_FAIL = "DELETING_GAME_FAIL";

export const FETCHING_CURRENT_GAME = "FETCHING_CURRENT_GAME";
export const FETCHING_CURRENT_GAME_SUCCESS = "FETCHING_CURRENT_GAME_SUCCESS";
export const RESET_CURRENT_GAME = "RESET_CURRENT_GAME";
export const ADD_PLAYER_TO_CURRENT_GAME = "ADD_PLAYER_TO_CURRENT_GAME";
export const ADD_WINNER = "ADD_WINNER";

export * from "./auth";
export * from "./game";
export * from "./games";
